modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Creative%20Block%20Replacer"
logoFile="icon.png"

[[mods]]
modId="creativeblockreplacer"
version="2.2"
displayName="Creative Block Replacer"
displayURL="https://serilum.com/mod/creative-block-replacer"
authors="Rick South"
description='''Allows easy switching in between placing and replacing blocks in creative mode.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.creativeblockreplacer]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativeblockreplacer]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "creativeblockreplacer_neoforge.mixins.json"